//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rectify11Installer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rectify11 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rectify11() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rectify11Installer.Strings.Rectify11", typeof(Rectify11).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string buttonAgree {
            get {
                return ResourceManager.GetString("buttonAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string buttonInstall {
            get {
                return ResourceManager.GetString("buttonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string buttonNext {
            get {
                return ResourceManager.GetString("buttonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        internal static string buttonReboot {
            get {
                return ResourceManager.GetString("buttonReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Context Menus.
        /// </summary>
        internal static string cmenuClassic {
            get {
                return ResourceManager.GetString("cmenuClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Menus with transparency.
        /// </summary>
        internal static string cmenuClassicA {
            get {
                return ResourceManager.GetString("cmenuClassicA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Fluent Menus (More Options).
        /// </summary>
        internal static string cmenuFluent1 {
            get {
                return ResourceManager.GetString("cmenuFluent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Fluent Menus (All Items in root).
        /// </summary>
        internal static string cmenuFluent2 {
            get {
                return ResourceManager.GetString("cmenuFluent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu style.
        /// </summary>
        internal static string CMenuPageHeader {
            get {
                return ResourceManager.GetString("CMenuPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a restore point.
        /// </summary>
        internal static string createRestore {
            get {
                return ResourceManager.GetString("createRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Enhanced Ribbon.
        /// </summary>
        internal static string epEnhRibbon {
            get {
                return ResourceManager.GetString("epEnhRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Mica to explorer navigation bar.
        /// </summary>
        internal static string epExtMica {
            get {
                return ResourceManager.GetString("epExtMica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your Desktop.
        /// </summary>
        internal static string epHeader {
            get {
                return ResourceManager.GetString("epHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your desired desktop experience.
        /// </summary>
        internal static string epTitle {
            get {
                return ResourceManager.GetString("epTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10 Rounded.
        /// </summary>
        internal static string epW10Radio {
            get {
                return ResourceManager.GetString("epW10Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10 Taskbar.
        /// </summary>
        internal static string epW10Taskbar {
            get {
                return ResourceManager.GetString("epW10Taskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 11 Default.
        /// </summary>
        internal static string epW11Radio {
            get {
                return ResourceManager.GetString("epW11Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        internal static string eulaPageHeader {
            get {
                return ResourceManager.GetString("eulaPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\pard{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}\fi-360\li360\f0\fs20{\pntext\f0 1.\tab}This software is provided &apos;as-is&apos;, without any express or implied warranty. In NO event will the author be held liable for any damages arising from the use of this software.\par{\pntext\f0 2.\tab}Rectify11 is free to use by anyone, but you cannot sell it. You cannot bundle this product as a part of another product without written permission from the author.\par{\pntext\f0 3.\tab}You cannot claim  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eulaR11 {
            get {
                return ResourceManager.GetString("eulaR11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can install Rectify11, you must agree to this license agreement:.
        /// </summary>
        internal static string eulaTitle {
            get {
                return ResourceManager.GetString("eulaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the installation?.
        /// </summary>
        internal static string exitText {
            get {
                return ResourceManager.GetString("exitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color Colorizing.
        /// </summary>
        internal static string installASDF {
            get {
                return ResourceManager.GetString("installASDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose what will be Rectified..
        /// </summary>
        internal static string installChoiceDescription {
            get {
                return ResourceManager.GetString("installChoiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to install.
        /// </summary>
        internal static string installChoiceTitle {
            get {
                return ResourceManager.GetString("installChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectified Gadgets.
        /// </summary>
        internal static string installGadgets {
            get {
                return ResourceManager.GetString("installGadgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Icons.
        /// </summary>
        internal static string installIcons {
            get {
                return ResourceManager.GetString("installIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip MicaForEveryone installation.
        /// </summary>
        internal static string installMFE {
            get {
                return ResourceManager.GetString("installMFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mica Alt instead of Mica.
        /// </summary>
        internal static string installMicaAlt {
            get {
                return ResourceManager.GetString("installMicaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectify your current Windows installation..
        /// </summary>
        internal static string installNote {
            get {
                return ResourceManager.GetString("installNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced context menus.
        /// </summary>
        internal static string installShell {
            get {
                return ResourceManager.GetString("installShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Themes.
        /// </summary>
        internal static string installThemes {
            get {
                return ResourceManager.GetString("installThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string installTitle {
            get {
                return ResourceManager.GetString("installTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remastered user avatars.
        /// </summary>
        internal static string installUserAV {
            get {
                return ResourceManager.GetString("installUserAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectify11 Wallpapers.
        /// </summary>
        internal static string installWallpapers {
            get {
                return ResourceManager.GetString("installWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Winver.
        /// </summary>
        internal static string installWinver {
            get {
                return ResourceManager.GetString("installWinver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add features to your existing installation..
        /// </summary>
        internal static string modifyNote {
            get {
                return ResourceManager.GetString("modifyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string modifyTitle {
            get {
                return ResourceManager.GetString("modifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string optionExtra {
            get {
                return ResourceManager.GetString("optionExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System icons.
        /// </summary>
        internal static string optionIcons {
            get {
                return ResourceManager.GetString("optionIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string optionThemes {
            get {
                return ResourceManager.GetString("optionThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know.
        /// </summary>
        internal static string progressText {
            get {
                return ResourceManager.GetString("progressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon r11 {
            get {
                object obj = ResourceManager.GetObject("r11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close everything and save your work as a reboot will be required at the end of the installation..
        /// </summary>
        internal static string summaryFooter {
            get {
                return ResourceManager.GetString("summaryFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string summaryHeader {
            get {
                return ResourceManager.GetString("summaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Rectify11 on this Windows installation..
        /// </summary>
        internal static string summaryItems {
            get {
                return ResourceManager.GetString("summaryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to do the following:.
        /// </summary>
        internal static string summaryTitle {
            get {
                return ResourceManager.GetString("summaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark with Mica.
        /// </summary>
        internal static string themeBlack {
            get {
                return ResourceManager.GetString("themeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your desired theme..
        /// </summary>
        internal static string themeChoiceTitle {
            get {
                return ResourceManager.GetString("themeChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string themeDark {
            get {
                return ResourceManager.GetString("themeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize your experience.
        /// </summary>
        internal static string themeHeader {
            get {
                return ResourceManager.GetString("themeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string themeLight {
            get {
                return ResourceManager.GetString("themeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectify11 Installer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose what will be restored..
        /// </summary>
        internal static string uninstallChoiceDescription {
            get {
                return ResourceManager.GetString("uninstallChoiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the original Windows look..
        /// </summary>
        internal static string uninstallNote {
            get {
                return ResourceManager.GetString("uninstallNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string uninstallTitle {
            get {
                return ResourceManager.GetString("uninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your existing Rectify11 installation..
        /// </summary>
        internal static string updateNote {
            get {
                return ResourceManager.GetString("updateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot install Rectify11 as Windows Updates are pending. Please reboot your system..
        /// </summary>
        internal static string updatePending {
            get {
                return ResourceManager.GetString("updatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateTitle {
            get {
                return ResourceManager.GetString("updateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install User avatars.
        /// </summary>
        internal static string userAvatars {
            get {
                return ResourceManager.GetString("userAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setup will go through the various steps required to install Rectify11 on your PC, for a more consistent experience. Select your desirable option to continue..
        /// </summary>
        internal static string welcomeDescription {
            get {
                return ResourceManager.GetString("welcomeDescription", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string optionBasic {
            get {
                return ResourceManager.GetString("optionBasic", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string optionAdvanced {
            get {
                return ResourceManager.GetString("optionAdvanced", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string restartNow {
            get {
                return ResourceManager.GetString("restartNow", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string restartLater {
            get {
                return ResourceManager.GetString("restartLater", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string previewTheme {
            get {
                return ResourceManager.GetString("previewTheme", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string themePartialDark {
            get {
                return ResourceManager.GetString("themePartialDark", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string compatErrorText {
            get {
                return ResourceManager.GetString("compatErrorText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string compatErrorInstruc {
            get {
                return ResourceManager.GetString("compatErrorInstruc", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string compatWarnText {
            get {
                return ResourceManager.GetString("compatWarnText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string compatWarnInstruc {
            get {
                return ResourceManager.GetString("compatWarnInstruc", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string moreInfo {
            get {
                return ResourceManager.GetString("moreInfo", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string lessInfo {
            get {
                return ResourceManager.GetString("lessInfo", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string uninstallConfirmText {
            get {
                return ResourceManager.GetString("uninstallConfirmText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string rtInstallFailPart1 {
            get {
                return ResourceManager.GetString("rtInstallFailPart1", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string rtInstallFailPart2 {
            get {
                return ResourceManager.GetString("rtInstallFailPart2", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string rtInstallFailInstruc {
            get {
                return ResourceManager.GetString("rtInstallFailInstruc", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string preparingInstall {
            get {
                return ResourceManager.GetString("preparingInstall", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string creatingRestorePoint {
            get {
                return ResourceManager.GetString("creatingRestorePoint", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string installingRt {
            get {
                return ResourceManager.GetString("installingRt", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string installingThemes {
            get {
                return ResourceManager.GetString("installingThemes", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string installingExtras {
            get {
                return ResourceManager.GetString("installingExtras", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string creatingUninstaller {
            get {
                return ResourceManager.GetString("creatingUninstaller", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string cleaningUp {
            get {
                return ResourceManager.GetString("cleaningUp", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string uninstallingIcons {
            get {
                return ResourceManager.GetString("uninstallingIcons", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string uninstallingThemes {
            get {
                return ResourceManager.GetString("uninstallingThemes", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string uninstallingExtras {
            get {
                return ResourceManager.GetString("uninstallingExtras", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string doneYouCanClose {
            get {
                return ResourceManager.GetString("doneYouCanClose", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string changedEverythingTitle {
            get {
                return ResourceManager.GetString("changedEverythingTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string changedEverythingText {
            get {
                return ResourceManager.GetString("changedEverythingText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterDpiTitle {
            get {
                return ResourceManager.GetString("betterDpiTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterDpiText {
            get {
                return ResourceManager.GetString("betterDpiText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterThemeTitle {
            get {
                return ResourceManager.GetString("betterThemeTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterThemeText {
            get {
                return ResourceManager.GetString("betterThemeText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterPerfTitle {
            get {
                return ResourceManager.GetString("betterPerfTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterPerfText {
            get {
                return ResourceManager.GetString("betterPerfText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterCplTitle {
            get {
                return ResourceManager.GetString("betterCplTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string betterCplText {
            get {
                return ResourceManager.GetString("betterCplText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string supportTitle {
            get {
                return ResourceManager.GetString("supportTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string thankYouTitle {
            get {
                return ResourceManager.GetString("thankYouTitle", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string thankYouText {
            get {
                return ResourceManager.GetString("thankYouText", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string restartingYourPC {
            get {
                return ResourceManager.GetString("restartingYourPC", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string uninstallFinishedPrompt {
            get {
                return ResourceManager.GetString("uninstallFinishedPrompt", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string installFinishedPrompt {
            get {
                return ResourceManager.GetString("installFinishedPrompt", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string r11InstallErrorPart1 {
            get {
                return ResourceManager.GetString("r11InstallErrorPart1", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string r11InstallErrorPart2 {
            get {
                return ResourceManager.GetString("r11InstallErrorPart2", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string r11UninstallThanks {
            get {
                return ResourceManager.GetString("r11UninstallThanks", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string r11UninstallSubTitle {
            get {
                return ResourceManager.GetString("r11UninstallSubTitle", resourceCulture);
            }
        }

 		/// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string tooNewBuild {
            get {
                return ResourceManager.GetString("tooNewBuild", resourceCulture);
            }
        }
    }
}
